name: Release Python Package

on:
  push:
    branches: [main, master]
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.12.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.10"

      - name: Configure git identity (para semantic-release)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install base deps (requirements.txt)
        if: hashFiles('requirements.txt') != ''
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # === NUEVO: instalar el paquete y dependencias de test ===
      - name: Install package (editable)
        run: |
          pip install -e .

      - name: Install test deps (requirements-dev.txt si existe)
        if: hashFiles('requirements-dev.txt') != ''
        run: |
          pip install -r requirements-dev.txt

      - name: Install pytest (fallback si no hay requirements-dev.txt)
        if: hashFiles('requirements-dev.txt') == ''
        run: |
          pip install pytest

      - name: Run unit tests
        run: |
          pytest -q
      # === FIN NUEVO ===
      - name: Install build & release tooling
        run: |
          pip install --upgrade build twine python-semantic-release

      - name: Bump version & tag (semantic-release)
        id: semver
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          semantic-release version
          TAG="$(git describe --tags --abbrev=0)"
          echo "TAG=$TAG" >> $GITHUB_ENV
          VERSION="${TAG#v}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build distribution
        run: |
          rm -rf dist/
          python -m build

      - name: Upload to PyPI
        if: ${{ env.PYPI_API_TOKEN != '' }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ env.PYPI_API_TOKEN }}
        run: python -m twine upload dist/*

      - name: Create GitHub Release and upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          files: |
            dist/*.whl
            dist/*.tar.gz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
