# .github/workflows/pr-tests.yml
name: PR Tests

on:
  push: # ← también al “subirlo a GitHub”
    branches:
      - "**"
  pull_request:
    branches: [main, master]

permissions:
  contents: read

concurrency:
  group: pr-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install base deps (requirements.txt)
        if: hashFiles('requirements.txt') != ''
        run: pip install -r requirements.txt

      - name: Install package (editable)
        run: pip install -e .

      - name: Install test deps (requirements-dev.txt si existe)
        if: hashFiles('requirements-dev.txt') != ''
        run: pip install -r requirements-dev.txt

      - name: Install pytest (fallback)
        if: hashFiles('requirements-dev.txt') == ''
        run: pip install pytest

      - name: Run unit tests (pytest)
        run: |
          pytest --maxfail=1 --disable-warnings -q --junitxml=pytest-report.xml

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report-${{ matrix.python-version }}
          path: pytest-report.xml
