name: Tag merged release commit

on:
  push:
    branches: [main, master]

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Extrae la versión SOLO si el commit trae "chore(release): vX.Y.Z"
      - name: Extract version from commit message
        id: v
        env:
          MSG: ${{ github.event.head_commit.message }}
        run: |
          VERSION=$(echo "$MSG" | sed -n 's/.*chore(release): v\([0-9][0-9.]*\).*/\1/p')
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Create and push tag
        if: ${{ steps.v.outputs.version != '' }}
        run: |
          git tag "v${{ steps.v.outputs.version }}"
          git push origin "v${{ steps.v.outputs.version }}"
